
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import LocalizationProviderWrapper from '@/components/LocalizationProvider';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
        <LocalizationProviderWrapper>
            <body className={inter.className}>
                <div className = 'flex'>
                    {children}
                </div>
            </body>
        </LocalizationProviderWrapper>
    </html>
  )
}
