<<<<<<< HEAD
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavbarStudent from "@/components/Navbar_student";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
=======
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
>>>>>>> f6e757d9bb3620e9abc8653d4db1b8e34df8bd36

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
<<<<<<< HEAD
      <body className={inter.className}>
      <div className = 'flex'>
      {children}
      </div>
      </body>
=======
      <body>{children}</body>
>>>>>>> f6e757d9bb3620e9abc8653d4db1b8e34df8bd36
    </html>
  )
}
