import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AuthProvider } from '../context/authContext';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Scholar's Saga",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <div className='flex'>
            {children}
          </div>
        </AuthProvider>
      </body>
    </html>
  )
}
