import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { getServerSession } from "next-auth";
import Link from "next/link";
import SignOut from "@/components/SignOut";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          {!!session && <SignOut />}
          {!session &&
          <Link href="/auth/sign-in">
            Sign In
          </Link>
          }
        </nav>
      <div className = 'flex'>
      {children}
      </div>
      </body>
    </html>
  )
}
